version: "3"
services:
  backend:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "6000:8080"
    env_file:
      - .env
    command: node dist/server.js
    restart: on-failure
